services:
  db:
    image: postgres:13.0
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: psu_loan
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - postgres_data:/var/lib/postgresql/data 
    restart: always

volumes:
  postgres_data: